//===============================================

export const ADD_BOARD_SUCCEEDED = 'ADD_BOARD_SUCCEEDED'
export const ADD_BOARD_FAILED = 'ADD_BOARD_FAILED'
export const ADD_BOARD_REQUESTED = 'ADD_BOARD_REQUESTED'

export const ADD_MEMBER_SUCCEEDED = 'ADD_MEMBER_SUCCEEDED'
export const ADD_MEMBERS_REQUESTED = 'ADD_MEMBER_REQUESTED'
export const FETCH_MEMBERS_REQUESTED = 'FETCH_MEMBERS_REQUESTED'
export const FETCH_MEMBERS_SUCCEEDED = 'FETCH_MEMBERS_SUCCEEDED'
