//===============================================

export const ADD_BOARD_SUCCEEDED = 'ADD_BOARD_SUCCEEDED'
export const ADD_BOARD_FAILED = 'ADD_BOARD_FAILED'
export const ADD_BOARD_REQUESTED = 'ADD_BOARD_REQUESTED'

export const ADD_MEMBER_SUCCEEDED = 'ADD_MEMBER_SUCCEEDED'
export const ADD_MEMBER_REQUESTED = 'ADD_MEMBER_REQUESTED'
export const FETCH_MEMBER_SUCCEEDED = 'ADD_MEMBER_SUCCEEDED'
export const FETCH_MEMBER_REQUESTED = 'ADD_MEMBER_REQUESTED'
